### ISSUE TITLE
Net.interfaces not working for palo alto devices 

### ISSUE THREAD

**Issue by shanmukha511** [napalm-automation/napalm-salt#56]
Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 167, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/napalm_panos/panos.py", line 528, in get_interfaces
            interface_info_json = json.dumps(interface_info_xml['response']['result']['hw'])
        KeyError: u'hw'
 The panos.py code is working fine for some devices but for some device when we execute net.interfaces we are getting above error

**Comment by itdependsnetworks** [comment]
Can you open the issue on the community panos driver? Please note the version of palo device that fails you are using when you do open the request
